---
- name: install jenkins
  host: localhost
  become: yes
  become_user: root
  tasks:
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
  - name: Download jenkins key
    get_url:
      name: download jenkins key
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc
  - name: Add jenkinsrep
    apt_repository:
      repo: deb signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins.list 
  
  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
  - name: install fontconfig to install java
    shell: apt install fontconfig -y
  - name: install java
    shell: apt install fontconfig openjdk-17-jre -y
  - name: install jenkins
    apt:
      name: jenkins
      state: present
  - name: start jenkins service
    apt:
      name: jenkins
      state: restarted
      enable: yes
